#! /usr/bin/ruby

require_relative 'includes/prompt'
require_relative 'includes/letters'
require_relative 'includes/card'
require_relative 'includes/dice'
require_relative 'includes/timer'
require_relative 'includes/bomb'

$wavPlayer = "paplay"

Letters.init
Signal.trap("INT") { puts "\nexitting!"; exit 0 }

card = nil
dice = nil

begin

  Prompt.proceed {
    if card.nil?
      puts "HELLO, BOOMER!"
    else
      puts "GAME OVER, BOOMER!"
    end
    puts
    puts "START GAME <<<"
  }

  Prompt.proceed(true) {
    card = Card.new
    puts " karta: #{card} <<<"
    puts "kostka:"
    puts
  }

  Prompt.proceed(true) {
    dice = Dice.new
    puts " karta: #{card}"
    puts "kostka: #{dice} <<<"
    puts
  }

  Prompt.proceed {
    puts " karta: #{card}"
    puts "kostka: #{dice}"
    puts "START?! <<<"
  }

  puts

  timer = Timer.new(40, 80)
  Bomb.new(timer)

end while true
